language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  include:
    - php: 5.5
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - php vendor/bin/phpunit -c phpunit.xml

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml
